name: date_range_form_field
description: A Flutter package to create a widget which allows the user to use a date picker to input a DateRange into a FormField using showDateRangePicker.
version: 1.0.2
homepage: https://github.com/JMAConsulting/date_range_form_field

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: '>=0.17.0 <1.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
